project:
  version: @project.version@
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
management.endpoints.web.exposure.include: '*'
logging:
  level:
    com.mydataway: debug
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: false
      directory: logs
      pattern: common
      prefix: access_log
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 10240
zuul:
  host:
    socket-timeout-millis: 50000
    connect-timeout-millis: 60000
  sensitive-headers:
  add-host-header: true
  include-debug-header: true
  routes:
    demo1:
      path: /demo1/**
      service-id: demo1
    demo2:
      path: /demo2/**
      service-id: demo2
    xxl-job-admin:
      path: /xxl-job/**
      service-id: xxl-job-admin
ribbon:
  http:
    client:
      enabled: false # 默认开启需要禁用
  okhttp:
    enabled: false
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true